// DealVerse front-end — no framework, no build tools needed in the browser.
// Reads /data/products.json and /data/categories.json (generated by build.js
// from the individual files the admin panel writes) and renders the UI.

async function loadJSON(path) {
  const res = await fetch(path, { cache: 'no-store' });
  if (!res.ok) return [];
  return res.json();
}

function money(n) {
  return '$' + Number(n).toFixed(2);
}

function productCard(p) {
  const link = `/product.html?slug=${encodeURIComponent(p.slug)}`;
  return `
  <div class="card">
    <a class="thumb" href="${link}">
      <img src="${p.image}" alt="${p.title}" loading="lazy">
      <span class="badge">-${p.discount_percent}%</span>
    </a>
    <div class="body">
      <span class="cat-label">${p.category}</span>
      <h3><a href="${link}">${p.title}</a></h3>
      <p class="desc">${p.short_description || ''}</p>
      <div class="price-row">
        <span class="price-now price">${money(p.price_now)}</span>
        <span class="price-was">${money(p.price_original)}</span>
      </div>
      ${p.rating ? `<span class="rating">★ ${p.rating.toFixed(1)}</span>` : ''}
      <a class="btn gold" href="${link}">See Deal</a>
    </div>
  </div>`;
}

function renderGrid(el, products) {
  if (!el) return;
  el.innerHTML = products.length
    ? products.map(productCard).join('')
    : `<p style="color:var(--ink-light)">No deals found. Try a different category or search term.</p>`;
}

function renderCategoryStrip(el, categories, activeSlug) {
  if (!el) return;
  const all = `<a class="cat-pill${!activeSlug ? ' active' : ''}" href="/index.html">All Deals</a>`;
  el.innerHTML = all + categories.map(c =>
    `<a class="cat-pill${activeSlug === c.slug ? ' active' : ''}" href="/category.html?cat=${encodeURIComponent(c.slug)}">${c.icon || ''} ${c.title}</a>`
  ).join('');
}

function qs(name) {
  return new URLSearchParams(window.location.search).get(name);
}

function attachSearch(inputEl, allProducts, gridEl) {
  if (!inputEl) return;
  inputEl.addEventListener('input', () => {
    const q = inputEl.value.trim().toLowerCase();
    const filtered = !q ? allProducts : allProducts.filter(p =>
      p.title.toLowerCase().includes(q) ||
      (p.category || '').toLowerCase().includes(q) ||
      (p.short_description || '').toLowerCase().includes(q)
    );
    renderGrid(gridEl, filtered);
  });
}

// ---- Page initializers ----

async function initHomePage() {
  const [products, categories] = await Promise.all([
    loadJSON('/data/products.json'),
    loadJSON('/data/categories.json')
  ]);
  renderCategoryStrip(document.getElementById('cat-strip'), categories, null);
  renderGrid(document.getElementById('featured-grid'), products.filter(p => p.featured));
  renderGrid(document.getElementById('all-grid'), products);
  attachSearch(document.getElementById('search-input'), products, document.getElementById('all-grid'));
}

async function initCategoryPage() {
  const catSlug = qs('cat');
  const [products, categories] = await Promise.all([
    loadJSON('/data/products.json'),
    loadJSON('/data/categories.json')
  ]);
  const cat = categories.find(c => c.slug === catSlug);
  const filtered = catSlug ? products.filter(p => (p.category || '').toLowerCase() === (cat ? cat.title.toLowerCase() : catSlug.toLowerCase())) : products;
  document.getElementById('cat-title').textContent = cat ? cat.title : 'All Deals';
  renderCategoryStrip(document.getElementById('cat-strip'), categories, catSlug);
  renderGrid(document.getElementById('cat-grid'), filtered);
  attachSearch(document.getElementById('search-input'), filtered, document.getElementById('cat-grid'));
}

async function initProductPage() {
  const slug = qs('slug');
  const products = await loadJSON('/data/products.json');
  const p = products.find(x => x.slug === slug);
  const el = document.getElementById('product-root');
  if (!p) {
    el.innerHTML = `<p style="padding:60px 0">Sorry, this deal is no longer available. <a href="/index.html">See other deals →</a></p>`;
    return;
  }
  document.title = `${p.title} — DealVerse`;
  el.innerHTML = `
    <div class="product-detail">
      <div><img src="${p.image}" alt="${p.title}"></div>
      <div>
        <span class="cat-label">${p.category}</span>
        <h1>${p.title}</h1>
        ${p.rating ? `<span class="rating">★ ${p.rating.toFixed(1)} rating</span>` : ''}
        <div class="pd-price">
          <span class="now price">${money(p.price_now)}</span>
          <span class="was">${money(p.price_original)}</span>
          <span class="badge" style="position:static;transform:none;">-${p.discount_percent}%</span>
        </div>
        <p>${(p.description || p.short_description || '').replace(/\n/g, '<br>')}</p>
        <a class="btn gold" style="font-size:16px;padding:14px 22px;" href="${p.affiliate_url}" target="_blank" rel="nofollow sponsored noopener">Get This Deal →</a>
        <p class="disclosure-note">As an Amazon Associate / affiliate partner, DealVerse earns from qualifying purchases made through links on this page — at no extra cost to you. <a href="/affiliate-disclosure.html">Learn more</a>.</p>
      </div>
    </div>`;

  // Related products from the same category
  const related = products.filter(x => x.category === p.category && x.slug !== p.slug).slice(0, 4);
  const relEl = document.getElementById('related-grid');
  if (relEl) renderGrid(relEl, related);
}

// Minimal markdown -> HTML for legal page bodies (bold + paragraphs only,
// enough for the CMS-edited legal text without pulling in a markdown library).
function mdLite(text) {
  if (!text) return '';
  return text
    .split(/\n\n+/)
    .map(block => {
      if (/^\*\*(.+)\*\*$/.test(block.trim())) {
        return `<h2>${block.trim().replace(/^\*\*(.+)\*\*$/, '$1')}</h2>`;
      }
      const withBold = block.replace(/\*\*(.+?)\*\*/g, '<strong>$1</strong>');
      return `<p>${withBold.replace(/\n/g, '<br>')}</p>`;
    })
    .join('\n');
}

async function initLegalPage(jsonPath, rootId) {
  const data = await loadJSON(jsonPath);
  const el = document.getElementById(rootId);
  if (el && data) el.innerHTML = mdLite(data.body);
}

async function initFooterCategories() {
  const el = document.getElementById('footer-cats');
  if (!el) return;
  const categories = await loadJSON('/data/categories.json');
  el.innerHTML = categories.slice(0, 6).map(c =>
    `<a href="/category.html?cat=${encodeURIComponent(c.slug)}">${c.title}</a>`
  ).join('');
}

document.addEventListener('DOMContentLoaded', () => {
  const btn = document.getElementById('mobile-menu-btn');
  const nav = document.querySelector('nav.main-nav');
  if (btn && nav) {
    btn.addEventListener('click', () => nav.classList.toggle('open'));
  }
});
// ═══ MOBILE NAV TOGGLE ═══
document.addEventListener('DOMContentLoaded', function () {
  const btn = document.getElementById('mobile-menu-btn');
  const nav = document.querySelector('.main-nav');

  if (btn && nav) {
    btn.addEventListener('click', function () {
      nav.classList.toggle('nav-open');
      const isOpen = nav.classList.contains('nav-open');
      btn.setAttribute('aria-expanded', isOpen);
    });

    // اقفل القائمة لو المستخدم دوس بره أي حتة فيها
    document.addEventListener('click', function (e) {
      if (!nav.contains(e.target) && !btn.contains(e.target)) {
        nav.classList.remove('nav-open');
      }
    });
  }
});
