// DealVerse front-end — no framework, no build tools needed in the browser.
// Reads /data/products.json and /data/categories.json (generated by build.js
// from the individual files the admin panel writes) and renders the UI.

async function loadJSON(path) {
  const res = await fetch(path, { cache: 'no-store' });
  if (!res.ok) return [];
  return res.json();
}

function money(n) {
  return '$' + Number(n).toFixed(2);
}

// Updates (or creates) the page's <meta name="description"> tag so blog post
// pages get a unique, relevant description for search engines.
function setMetaDescription(text) {
  if (!text) return;
  let tag = document.querySelector('meta[name="description"]');
  if (!tag) {
    tag = document.createElement('meta');
    tag.setAttribute('name', 'description');
    document.head.appendChild(tag);
  }
  tag.setAttribute('content', text.slice(0, 160));
}

function productCard(p) {
  const link = `/product.html?slug=${encodeURIComponent(p.slug)}`;
  return `
  <div class="card">
    <a class="thumb" href="${link}">
      <img src="${p.image}" alt="${p.title}" loading="lazy">
      <span class="badge">-${p.discount_percent}%</span>
    </a>
    <div class="body">
      <span class="cat-label">${p.category}</span>
      <h3><a href="${link}">${p.title}</a></h3>
      <p class="desc">${p.short_description || ''}</p>
      <div class="price-row">
        <span class="price-now price">${money(p.price_now)}</span>
        <span class="price-was">${money(p.price_original)}</span>
      </div>
      ${p.rating ? `<span class="rating">★ ${p.rating.toFixed(1)}</span>` : ''}
      <a class="btn gold" href="${link}">See Deal</a>
    </div>
  </div>`;
}

function renderGrid(el, products) {
  if (!el) return;
  el.innerHTML = products.length
    ? products.map(productCard).join('')
    : `<p style="color:var(--ink-light)">No deals found. Try a different category or search term.</p>`;
}

function renderCategoryStrip(el, categories, activeSlug) {
  if (!el) return;
  const all = `<a class="cat-pill${!activeSlug ? ' active' : ''}" href="/index.html">All Deals</a>`;
  el.innerHTML = all + categories.map(c =>
    `<a class="cat-pill${activeSlug === c.slug ? ' active' : ''}" href="/category.html?cat=${encodeURIComponent(c.slug)}">${c.icon || ''} ${c.title}</a>`
  ).join('');
}

function qs(name) {
  return new URLSearchParams(window.location.search).get(name);
}

function attachSearch(inputEl, allProducts, gridEl) {
  if (!inputEl) return;
  inputEl.addEventListener('input', () => {
    const q = inputEl.value.trim().toLowerCase();
    const filtered = !q ? allProducts : allProducts.filter(p =>
      p.title.toLowerCase().includes(q) ||
      (p.category || '').toLowerCase().includes(q) ||
      (p.short_description || '').toLowerCase().includes(q)
    );
    renderGrid(gridEl, filtered);
  });
}

// ---- Page initializers ----

async function initHomePage() {
  const [products, categories] = await Promise.all([
    loadJSON('/data/products.json'),
    loadJSON('/data/categories.json')
  ]);
  renderCategoryStrip(document.getElementById('cat-strip'), categories, null);
  renderGrid(document.getElementById('featured-grid'), products.filter(p => p.featured));
  renderGrid(document.getElementById('all-grid'), products);
  attachSearch(document.getElementById('search-input'), products, document.getElementById('all-grid'));
}

async function initCategoryPage() {
  const catSlug = qs('cat');
  const [products, categories] = await Promise.all([
    loadJSON('/data/products.json'),
    loadJSON('/data/categories.json')
  ]);
  const cat = categories.find(c => c.slug === catSlug);
  const filtered = catSlug ? products.filter(p => (p.category || '').toLowerCase() === (cat ? cat.title.toLowerCase() : catSlug.toLowerCase())) : products;
  document.getElementById('cat-title').textContent = cat ? cat.title : 'All Deals';
  renderCategoryStrip(document.getElementById('cat-strip'), categories, catSlug);
  renderGrid(document.getElementById('cat-grid'), filtered);
  attachSearch(document.getElementById('search-input'), filtered, document.getElementById('cat-grid'));
}

async function initProductPage() {
  const slug = qs('slug');
  const products = await loadJSON('/data/products.json');
  const p = products.find(x => x.slug === slug);
  const el = document.getElementById('product-root');
  if (!p) {
    el.innerHTML = `<p style="padding:60px 0">Sorry, this deal is no longer available. <a href="/index.html">See other deals →</a></p>`;
    return;
  }
  document.title = `${p.title} — StoreForLess`;
  el.innerHTML = `
    <div class="product-detail">
      <div><img src="${p.image}" alt="${p.title}"></div>
      <div>
        <span class="cat-label">${p.category}</span>
        <h1>${p.title}</h1>
        ${p.rating ? `<span class="rating">★ ${p.rating.toFixed(1)} rating</span>` : ''}
        <div class="pd-price">
          <span class="now price">${money(p.price_now)}</span>
          <span class="was">${money(p.price_original)}</span>
          <span class="badge" style="position:static;transform:none;">-${p.discount_percent}%</span>
        </div>
        <p>${(p.description || p.short_description || '').replace(/\n/g, '<br>')}</p>
        <a id="affiliate-cta" class="btn gold" style="font-size:16px;padding:14px 22px;" href="${p.affiliate_url}" target="_blank" rel="nofollow sponsored noopener" data-title="${p.title}" data-category="${p.category}" data-slug="${p.slug}" data-price="${p.price_now}">Get This Deal →</a>
        <p class="disclosure-note">As an Amazon Associate / affiliate partner, StoreForLess earns from qualifying purchases made through links on this page — at no extra cost to you. <a href="/affiliate-disclosure.html">Learn more</a>.</p>
        ${p.date_added ? `<p class="last-verified">Last verified: ${new Date(p.date_added).toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}</p>` : ''}
      </div>
    </div>`;

  renderProductSchema(p);

  // Related products from the same category
  const related = products.filter(x => x.category === p.category && x.slug !== p.slug).slice(0, 4);
  const relEl = document.getElementById('related-grid');
  if (relEl) renderGrid(relEl, related);

  // Track affiliate link clicks as a GA4 key event
  const cta = document.getElementById('affiliate-cta');
  if (cta && typeof gtag === 'function') {
    cta.addEventListener('click', () => {
      gtag('event', 'affiliate_click', {
        item_name: cta.dataset.title,
        item_category: cta.dataset.category,
        item_slug: cta.dataset.slug,
        value: parseFloat(cta.dataset.price) || 0,
        currency: 'USD'
      });
    });
  }
}

// Minimal markdown -> HTML for legal page bodies (bold + paragraphs only,
// enough for the CMS-edited legal text without pulling in a markdown library).
// ═══ PRODUCT SCHEMA MARKUP (JSON-LD) ═══
function renderProductSchema(p) {
  const existing = document.getElementById('product-schema');
  if (existing) existing.remove();
  const schema = {
    "@context": "https://schema.org/",
    "@type": "Product",
    "name": p.title,
    "image": p.image,
    "description": p.short_description || p.description || p.title,
    "category": p.category,
    "offers": {
      "@type": "Offer",
      "url": window.location.href,
      "priceCurrency": "USD",
      "price": p.price_now,
      "availability": "https://schema.org/InStock"
    }
  };
  if (p.rating) {
    schema.aggregateRating = {
      "@type": "AggregateRating",
      "ratingValue": p.rating,
      "bestRating": "5",
      "reviewCount": "1"
    };
  }
  const script = document.createElement('script');
  script.type = 'application/ld+json';
  script.id = 'product-schema';
  script.textContent = JSON.stringify(schema);
  document.head.appendChild(script);
}

function mdLite(text) {
  if (!text) return '';
  return text
    .split(/\n\n+/)
    .map(block => {
      if (/^\*\*(.+)\*\*$/.test(block.trim())) {
        return `<h2>${block.trim().replace(/^\*\*(.+)\*\*$/, '$1')}</h2>`;
      }
      const withBold = block.replace(/\*\*(.+?)\*\*/g, '<strong>$1</strong>');
      return `<p>${withBold.replace(/\n/g, '<br>')}</p>`;
    })
    .join('\n');
}

async function initLegalPage(jsonPath, rootId) {
  const data = await loadJSON(jsonPath);
  const el = document.getElementById(rootId);
  if (el && data) el.innerHTML = mdLite(data.body);
}

async function initFooterCategories() {
  const el = document.getElementById('footer-cats');
  if (!el) return;
  const categories = await loadJSON('/data/categories.json');
  el.innerHTML = categories.slice(0, 6).map(c =>
    `<a href="/category.html?cat=${encodeURIComponent(c.slug)}">${c.title}</a>`
  ).join('');
}

function blogCard(post) {
  const link = `/blog-post.html?slug=${encodeURIComponent(post.slug)}`;
  const dateStr = post.date_published ? new Date(post.date_published).toLocaleDateString('en-US', { year: 'numeric', month: 'short', day: 'numeric' }) : '';
  return `
  <div class="card">
    <div class="body">
      <span class="cat-label">${post.category || ''}</span>
      <h3><a href="${link}">${post.title}</a></h3>
      <p class="desc">${post.excerpt || ''}</p>
      ${dateStr ? `<span style="color:var(--ink-light);font-size:13px;">${dateStr}</span>` : ''}
      <a class="btn gold" href="${link}">Read More</a>
    </div>
  </div>`;
}

async function initBlogPage() {
  const posts = await loadJSON('/data/blog.json');
  const el = document.getElementById('blog-grid');
  if (el) {
    el.innerHTML = posts.length
      ? posts.map(blogCard).join('')
      : `<p style="color:var(--ink-light)">No posts yet — check back soon.</p>`;
  }
}

async function initBlogPostPage() {
  const slug = qs('slug');
  const posts = await loadJSON('/data/blog.json');
  const post = posts.find(x => x.slug === slug);
  const el = document.getElementById('blog-post-root');
  if (!post) {
    if (el) el.innerHTML = `<p style="padding:40px 0">Sorry, this post is no longer available. <a href="/blog.html">See all posts →</a></p>`;
    return;
  }
  document.title = `${post.title} — StoreForLess`;
  setMetaDescription(post.excerpt || post.title);
  const dateStr = post.date_published ? new Date(post.date_published).toLocaleDateString('en-US', { year: 'numeric', month: 'short', day: 'numeric' }) : '';
  if (el) {
    el.innerHTML = `
      <span class="cat-label">${post.category || ''}</span>
      <h1>${post.title}</h1>
      <div class="updated">${post.author ? post.author + ' · ' : ''}${dateStr}</div>
      ${mdLite(post.body)}
    `;
  }

  const related = posts.filter(x => x.category === post.category && x.slug !== post.slug).slice(0, 3);
  const relEl = document.getElementById('related-blog-grid');
  if (relEl) relEl.innerHTML = related.length ? related.map(blogCard).join('') : '';
}

// ═══ MOBILE NAV TOGGLE ═══
document.addEventListener('DOMContentLoaded', function () {
  const btn = document.getElementById('mobile-menu-btn');
  const nav = document.querySelector('.main-nav');

  if (btn && nav) {
    btn.addEventListener('click', function () {
      nav.classList.toggle('nav-open');
      const isOpen = nav.classList.contains('nav-open');
      btn.setAttribute('aria-expanded', isOpen);
    });

    // اقفل القائمة لو المستخدم دوس بره أي حتة فيها
    document.addEventListener('click', function (e) {
      if (!nav.contains(e.target) && !btn.contains(e.target)) {
        nav.classList.remove('nav-open');
      }
    });
  }
});

// ═══ WHATSAPP FLOATING BUTTON ═══
function initWhatsAppButton() {
  const phone = '971582763958';
  const message = encodeURIComponent('Hi! I have a question about StoreForLess.');
  const a = document.createElement('a');
  a.href = `https://wa.me/${phone}?text=${message}`;
  a.className = 'whatsapp-float';
  a.target = '_blank';
  a.rel = 'noopener noreferrer';
  a.setAttribute('aria-label', 'Chat with us on WhatsApp');
  a.innerHTML = `<svg viewBox="0 0 32 32" width="28" height="28" fill="#fff"><path d="M16.004 3C9.376 3 3.997 8.373 3.997 15c0 2.32.646 4.49 1.77 6.34L3 29l7.86-2.73A11.94 11.94 0 0 0 16.004 27C22.63 27 28 21.627 28 15S22.63 3 16.004 3zm0 21.8c-1.99 0-3.85-.55-5.44-1.5l-.39-.23-4.66 1.62 1.55-4.54-.25-.4A9.7 9.7 0 0 1 5.2 15c0-5.96 4.85-10.8 10.8-10.8S26.8 9.04 26.8 15s-4.85 10.8-10.8 10.8zm5.95-8.1c-.33-.16-1.94-.96-2.24-1.07-.3-.11-.52-.16-.74.16-.22.33-.85 1.07-1.04 1.28-.19.22-.38.25-.71.08-.33-.16-1.38-.51-2.63-1.63-.97-.87-1.63-1.94-1.82-2.27-.19-.33-.02-.5.14-.67.15-.15.33-.38.5-.58.16-.19.22-.33.33-.55.11-.22.05-.41-.03-.58-.08-.16-.74-1.78-1.01-2.44-.27-.64-.54-.55-.74-.56h-.63c-.22 0-.58.08-.88.41-.3.33-1.15 1.12-1.15 2.74s1.18 3.18 1.34 3.4c.16.22 2.32 3.55 5.63 4.98.79.34 1.4.54 1.88.7.79.25 1.51.21 2.08.13.63-.09 1.94-.79 2.21-1.56.27-.77.27-1.43.19-1.56-.08-.14-.3-.22-.63-.38z"/></svg>`;
  document.body.appendChild(a);
}

document.addEventListener('DOMContentLoaded', initWhatsAppButton);
